site_name: Mukurtu User Manual

theme:
  name: material
  logo: _static/assets/logo.png
  favicon: _static/assets/favicon.ico
  custom_dir: docs/_overrides
  features:
    - search.suggest
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      accent: deep orange
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      accent: deep orange

copyright: Mukurtu CMS is managed by the Center for Digital Scholarship and Curation at Washington State University. Mukurtu CMS, Mukurtu Support resources, and all materials on mukurtu.org are distributed under the terms of the GNU General Public License version 3 (or "GPLv3"), which means anyone is free to download and share them with others. <p></p>

extra_css:
  - _static/style.css

plugins:
  - search
  - tags
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: auto
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false
  - exporter:
      formats:
        pdf:
          enabled: !ENV [MKDOCS_EXPORTER_PDF, false] #re-enable as true when ready
          concurrency: 8
          aggregator:
            enabled: false #re-enable as true when ready
            output: mukurtu-user-manual.pdf
            covers: all
      buttons:
        - title: Download as PDF
          icon: material-file-download-outline
          enabled: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.enabled
          attributes: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.attributes

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      
nav:
  - Style Guide: styleguide.md
  - 3Cs:
    - 3Cs/UnderstandingCommunitiesAndCulturalProtocols.md
    - 3Cs/CreateACommunityAndInitialCulturalProtocol.md
    - 3Cs/CreateACulturalProtocol.md 
    - 3Cs/UnderstandingSharingSettings.md
    - 3Cs/UnderstandingCategories.md
    - 3Cs/CreateCategories.md 
    - 3Cs/CategoryTaxonomy.md
    - 3Cs/EditCommunitySettings.md
    - 3Cs/EditCulturalProtocolSettings.md
  - Collections:
    - collections/UnderstandingCollections.md
    - collections/AddandArrangeCollections.md
    - collections/SubcollectionOrganization.md
    - collections/PersonalCollection.md
    - collections/CreateCollection.md 
  - DH Items:
    - digital-heritage-items/DHMetadataFields.md
    - digital-heritage-items/CreateDHItem.md
  - Dictionary:
    - dictionary/AddLanguage.md
  - FAQs:
    - faqs/DatabasePrivacy.md
  - Localization and Translation:
    - localization-translation/LocalizationTranslationOverview.md 
    - localization-translation/RequiredModules.md
  - Location:
    - location/mapping-test.md
  - Media:
    - media/UnderstandingMediaAssets.md 
    - media/CreateMediaAssets.md 
    - media/ByTypeMediaUpload.md
    - media/MediaAssetMetadata.md
    - media/MediaAssetFileFormats.md 
    - media/ManageMediaAccessWithProtocols.md 
    - media/VimeoPrivacySettings.md 
    - media/YoutubePrivacySettings.md
    - media/SoundCloudPrivacySettings.md 
    - media/MediaContentWarnings.md
  - Migration from Mukurtu 3 to Mukurtu 4: 
    - migration/00MigrationOverview.md
    - migration/01MigrationPlanning.md
    - migration/02UpdateMukurtu3.md
    - migration/03Pre-Migration.md
    - migration/04InstallMukurtu4.md
    - migration/05CopyMediaDirectory.md
    - migration/06RunMigrationTool.md
    - migration/07VerifyMigration.md
    - migration/08CompleteConfiguration.md
    - migration/09ConfirmSiteOperation.md
    - migration/10DecommissionMukurtu3.md
  - Person Records:
    - person-records/PersonRecords.md
    - person-records/ConfigurePersonRecord.md
  - Users:
    - users/users-intro.md
    - users/user-role-types.md 
    - users/creating-account.md 
    - users/managing-administrator-roles.md 
    - users/managing-user-roles.md 
  - Taxonomies:
    - taxonomies/UnderstandingTaxonomies.md
    - taxonomies/ManagingTaxonomies.md
  - Tags: tags.md
  - Download the User Manual: DownloadManual.md
