site_name: Mukurtu User Manual

theme:
  name: material
  logo: _static/assets/logo.png
  favicon: _static/assets/favicon.ico
  features:
    - search.suggest
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      accent: deep orange
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      accent: deep orange
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

copyright: Mukurtu CMS is managed by the Center for Digital Scholarship and Curation at Washington State University. Mukurtu CMS, Mukurtu Support resources, and all materials on mukurtu.org are distributed under the terms of the GNU General Public License version 3 (or "GPLv3"), which means anyone is free to download and share them with others. <p></p>

extra:
  tags: 
    media: media
    metadata: 
    roundtrip:
    users: 
    content: 

extra_css:
  - _static/style.css

plugins:
  - search
  - tags
  - exporter:
      formats:
        pdf:
          enabled: !ENV [MKDOCS_EXPORTER_PDF, true]
          concurrency: 8
          aggregator:
            enabled: true
            output: mukurtu-user-manual.pdf
            covers: all
      buttons:
        - title: Download as PDF
          icon: material-file-download-outline
          enabled: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.enabled
          attributes: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.attributes

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Style Guide: styleguide.md
  - 3Cs:
    - 3Cs/create-a-cultural-protocol.md 
    - 3Cs/creating-categories.md 
    - 3Cs/understanding-categories.md
    - 3Cs/Create-a-community-and-initial-cultural-protocol.md
  - Collections:
    - collections/CreateCollection.md 
    - collections/UnderstandingCollections.md
  - DH Items:
    - digital-heritage-items/DHMetadataFields.md
  - FAQs:
    - faqs/DatabasePrivacy.md
  - Localization and Translation:
    - localization-translation/LocalizationTranslationOverview.md 
    - localization-translation/RequiredModules.md
  - Media:
    - media/ManageMediaAccessWithProtocols.md 
    - media/MediaAssetFileFormats.md 
    - media/MediaAssetMetadata.md 
    - media/SoundCloudPrivacySettings.md 
    - media/UnderstandingMediaAssets.md 
    - media/upload-media-assets.md 
    - media/VimeoPrivacySettings.md 
    - media/YoutubePrivacySettings.md
  - Migration from Mukurtu 3 to Mukurtu 4: 
    - migration/00MigrationOverview.md
    - migration/01MigrationPlanning.md
    - migration/02UpdateMukurtu3.md
    - migration/03Pre-Migration.md
    - migration/04InstallMukurtu4.md
    - migration/05CopyMediaDirectory.md
    - migration/06RunMigrationTool.md
    - migration/07VerifyMigration.md
    - migration/08CompleteConfiguration.md
    - migration/09ConfirmSiteOperation.md
    - migration/10DecommissionMukurtu3.md
  - Users:
    - users/creating-account.md 
    - users/managing-administrator-roles.md 
    - users/managing-user-roles.md 
    - users/user-role-types.md 
    - users/users-intro.md
  - Tags: tags.md
  - PDF User Manual: mukurtu-user-manual.pdf
